apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-metabench-http
  labels:
    k8s-app: debug-metabench-http
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: debug-metabench-http
  template:
    metadata:
      labels:
        k8s-app: debug-metabench-http
    spec:
      containers:
        - image: hongweiruan/hugsim-base:latest
          name: hugsim-container
          command: ["sh", "-c", "sleep infinity"]
          resources:
            requests:
              cpu: "8"
              memory: "32Gi"
              ephemeral-storage: "50Gi"
            limits:
              cpu: "12"
              memory: "64Gi"
              ephemeral-storage: "100Gi"
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: hugsim-storage
              mountPath: /
            - name: avl-west-vol
              mountPath: /avl-west
            - name: closed-loop-e2e
              mountPath: /closed-loop-e2e
          env:
            - name: PIXI_CACHE_DIR
              value: "/workspace/.pixi_cache"
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: "8Gi"
        - name: hugsim-storage
          persistentVolumeClaim:
            claimName: horuan-hugsim-vol
        - name: avl-west-vol
          persistentVolumeClaim:
            claimName: avl-west-vol
        - name: closed-loop-e2e
          persistentVolumeClaim:
            claimName: closed-loop-e2e
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nvidia.com/gpu.product
                    operator: In
                    values:
                      - NVIDIA-GeForce-RTX-4090
                      - NVIDIA-GeForce-RTX-3090
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - ry-gpu-1.sdsc.optiputer.net
                      - ry-gpu-2.sdsc.optiputer.net
                      - ry-gpu-3.sdsc.optiputer.net
                      - ry-gpu-4.sdsc.optiputer.net
                      - ry-gpu-5.sdsc.optiputer.net
                      - ry-gpu-6.sdsc.optiputer.net
                      - ry-gpu-7.sdsc.optiputer.net
                      - ry-gpu-8.sdsc.optiputer.net
                      - ry-gpu-9.sdsc.optiputer.net
                      - ry-gpu-10.sdsc.optiputer.net
                      - ry-gpu-11.sdsc.optiputer.net
                      - ry-gpu-12.sdsc.optiputer.net
                      - ry-gpu-13.sdsc.optiputer.net
                      - ry-gpu-14.sdsc.optiputer.net
      tolerations:
        - effect: NoSchedule
          key: nautilus.io/reservation
          operator: Equal
          value: cogrob
