apiVersion: v1
kind: Pod
metadata:
  name: horuan-debug
  namespace: cogrob
  labels:
    k8s-app: horuan-debug
spec:
  restartPolicy: Never
  containers:
    - name: debug-container
      image: robinwangucsd/metabench:latest
      imagePullPolicy: Always
      command:
        - bash
        - -lc
      args:
        - sleep infinity
      resources:
        requests:
          cpu: "8"
        limits:
          cpu: "8"
      volumeMounts:
        - name: hugsim-storage
          mountPath: /hugsim-storage
  volumes:
    - name: hugsim-storage
      persistentVolumeClaim:
        claimName: horuan-hugsim-vol
