apiVersion: batch/v1
kind: Job
metadata:
  name: job-eval-navhard-drivor-idm-rr-${REPLAN_RATE}-ef-${EVAL_FRAMES}-${SPLIT}
  namespace: cogrob
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        k8s-app: job-eval-navhard-drivor-idm-rr-${REPLAN_RATE}-ef-${EVAL_FRAMES}-${SPLIT}
    spec:
      restartPolicy: Never
      containers:
        - name: gpu-container
          image: robinwangucsd/metabench:latest
          imagePullPolicy: Always
          command:
            - "sh"
            - "-c"
          args:
            - |
              echo "=== Copying MetaBench Cleaned ===" &&
              cp -r /hugsim-storage/MetaBench /root/MetaBench &&
              echo "=== Creating conda env ===" &&
              conda create -n mdsn python=3.9 pip -y &&
              echo "=== Installing metadrive ===" &&
              cd /root/MetaBench/metadrive && /opt/conda/envs/mdsn/bin/pip install -e .[cuda] &&
              echo "=== Installing torch ===" &&
              /opt/conda/envs/mdsn/bin/pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 &&
              echo "=== Installing cupy & cuda-python ===" &&
              /opt/conda/envs/mdsn/bin/pip install cupy-cuda11x &&
              /opt/conda/envs/mdsn/bin/pip install cuda-python &&
              mkdir /usr/lib/dri &&
              ln -s /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so /usr/lib/dri/swrast_dri.so &&
              ln -sf /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30 /opt/conda/envs/mdsn/lib/libstdc++.so.6 &&
              echo "=== Installing scenarionet ===" &&
              cd /root/MetaBench/scenarionet &&
              /opt/conda/envs/mdsn/bin/pip install -e . &&
              echo "=== Configuring panda3d ===" &&
              echo "model-path /root/MetaBench/metadrive/metadrive/assets/models/pedestrian" >> /opt/conda/envs/mdsn/lib/python3.9/site-packages/panda3d/etc/Config.prc &&
              echo "model-path /root/MetaBench/metadrive/metadrive/assets/models/traffic_cone" >> /opt/conda/envs/mdsn/lib/python3.9/site-packages/panda3d/etc/Config.prc &&
              echo "=== Installing remaining packages ===" &&
              /opt/conda/envs/mdsn/bin/pip install timm scipy nuplan-devkit pyyaml pyogrio rasterio aioboto3 retry numpy==1.23.4 pyquaternion pytest h5py diffusers einops omegaconf hydra-core joblib wandb pytorch-lightning timm imageio &&
              echo "=== Installing MetaBench (cleaned) ===" &&
              cd /root/MetaBench && /opt/conda/envs/mdsn/bin/pip install -e . &&
              echo "=== Starting eval: drivor ===" &&
              bash /closed-loop-e2e/experiments/scripts/run_eval_idm.sh \
                  drivor \
                  /closed-loop-e2e/weights/navsimv2/DrivoR/drivor_Nav2_10epochs.pth \
                  "" \
                  /avl-west/navsim/navhard_md_logs \
                  /closed-loop-e2e/experiments/zero_shot_results/eval_navhard_idm/drivor/split_${SPLIT}_rr_${REPLAN_RATE}_ef_${EVAL_FRAMES} \
                  ${REPLAN_RATE} \
                  ${EVAL_FRAMES} \
                  /closed-loop-e2e/navhard_test_split/${SPLIT}.txt
          resources:
            requests:
              cpu: "3"
              memory: "20Gi"
              nvidia.com/gpu: "1"
              ephemeral-storage: 100Gi
            limits:
              cpu: "4"
              memory: "24Gi"
              nvidia.com/gpu: "1"
              ephemeral-storage: 100Gi
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: avl-west-vol
              mountPath: /avl-west
            - name: closed-loop-e2e
              mountPath: /closed-loop-e2e
            - name: hugsim-storage
              mountPath: /hugsim-storage
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: avl-west-vol
          persistentVolumeClaim:
            claimName: avl-west-vol
        - name: closed-loop-e2e
          persistentVolumeClaim:
            claimName: closed-loop-e2e
        - name: hugsim-storage
          persistentVolumeClaim:
            claimName: horuan-hugsim-vol
      tolerations:
        - effect: NoSchedule
          key: nautilus.io/reservation
          operator: Equal
          value: cogrob
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: In
                    values:
                      - us-west
                  - key: nvidia.com/gpu.product
                    operator: In
                    values:
                      - NVIDIA-GeForce-RTX-4090
                      - NVIDIA-GeForce-RTX-3090
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      # - ry-gpu-01.sdsc.optiputer.net
                      # - ry-gpu-02.sdsc.optiputer.net
                      - ry-gpu-03.sdsc.optiputer.net
                      - ry-gpu-04.sdsc.optiputer.net
                      - ry-gpu-05.sdsc.optiputer.net
                      - ry-gpu-06.sdsc.optiputer.net
                      - ry-gpu-07.sdsc.optiputer.net
                      - ry-gpu-08.sdsc.optiputer.net
                      - ry-gpu-09.sdsc.optiputer.net
                      - ry-gpu-10.sdsc.optiputer.net
                      - ry-gpu-11.sdsc.optiputer.net
                      - ry-gpu-12.sdsc.optiputer.net
                      - ry-gpu-13.sdsc.optiputer.net
                      - ry-gpu-14.sdsc.optiputer.net
