apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: navsafe-eval
    worker: w04
    seed: '3'
  name: navsafe-eval-w04-s3
  namespace: cogrob
spec:
  backoffLimit: 4
  completionMode: NonIndexed
  completions: 1
  manualSelector: false
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  suspend: false
  template:
    metadata:
      labels:
        app: navsafe-eval
        worker: w04
        seed: '3'
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - ry-gpu-05.sdsc.optiputer.net
                - ry-gpu-06.sdsc.optiputer.net
                - ry-gpu-07.sdsc.optiputer.net
                - ry-gpu-08.sdsc.optiputer.net
                - ry-gpu-11.sdsc.optiputer.net
                - ry-gpu-12.sdsc.optiputer.net
                - ry-gpu-13.sdsc.optiputer.net
                - ry-gpu-14.sdsc.optiputer.net
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-GeForce-RTX-3090
      containers:
      - command:
        - /opt/nvidia/nvidia_entrypoint.sh
        - bash
        - /cfg/run_worker.sh
        env:
        - name: WORKER_INDEX
          value: '4'
        - name: WORKERS
          value: '25'
        - name: SEEDS
          value: '3'
        - name: NEXUSSIM_SHA
          value: 5f098ccc49e1983395b47d7b4112f21ef4dc714e
        - name: NGC_API_KEY
          valueFrom:
            secretKeyRef:
              key: NGC_API_KEY
              name: ngc-api-key
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              key: HF_TOKEN
              name: hf-token
        - name: HYDRA_FULL_ERROR
          value: '1'
        - name: ACCEPT_EULA
          value: 'Y'
        - name: OMNI_KIT_ACCEPT_EULA
          value: 'Y'
        image: nvcr.io/nvidia/nre/nre-ga@sha256:6e0caa70a9148490552520c3dde9ee665c8d094ca10b814601cb8bb306567c90
        imagePullPolicy: IfNotPresent
        name: eval
        resources:
          limits:
            cpu: '3'
            ephemeral-storage: 60Gi
            memory: 32Gi
            nvidia.com/gpu: '2'
          requests:
            cpu: '3'
            ephemeral-storage: 60Gi
            memory: 32Gi
            nvidia.com/gpu: '2'
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /cfg
          name: cfg
        - mountPath: /avl-west
          name: avl-west-vol
        - mountPath: /hugsim-storage
          name: hugsim-storage
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: ngc-pull
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: nautilus.io/reservation
        operator: Equal
        value: cogrob
      - effect: NoSchedule
        key: nautilus.io/cogrob
        operator: Exists
      volumes:
      - emptyDir:
          medium: Memory
          sizeLimit: 24Gi
        name: dshm
      - configMap:
          defaultMode: 420
          name: navsafe-eval-cfg
        name: cfg
      - name: avl-west-vol
        persistentVolumeClaim:
          claimName: avl-west-vol
      - name: hugsim-storage
        persistentVolumeClaim:
          claimName: horuan-hugsim-vol
  ttlSecondsAfterFinished: 259200
