apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: horuan-volume
spec:
  storageClassName: rook-cephfs # Use the CephFS storage class
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi