apiVersion: batch/v1
kind: Job
metadata:
  name: job-eval-navhard-dp-rr-${REPLAN_RATE}-ef-${EVAL_FRAMES}-${SPLIT}
  namespace: cogrob
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        k8s-app: job-eval-navhard-dp-rr-${REPLAN_RATE}-ef-${EVAL_FRAMES}-${SPLIT}
    spec:
      restartPolicy: Never
      containers:
        - name: gpu-container
          image: robinwangucsd/metabench:latest
          imagePullPolicy: Always
          command:
            - "sh"
            - "-c"
          args:
            - |
              cp -r /hugsim-storage/BridgeSim /root/BridgeSim &&
              cd /root/BridgeSim &&
              conda env create -f mdsn.yml &&
              /opt/conda/envs/mdsn/bin/pip install -e nuplan-devkit/ &&
              /opt/conda/envs/mdsn/bin/pip install -e metadrive/.[cuda] &&
              /opt/conda/envs/mdsn/bin/pip install -e . &&
              echo "=== Starting eval ===" &&
              bash /closed-loop-e2e/experiments/scripts/run_eval_BridgeSim.sh \
                  --model-type diffusion_planner \
                  --checkpoint /closed-loop-e2e/weights/nuplan/diffusionplanner/model.pth \
                  --scenario-base-path /hugsim-storage/state_based_convert_navhard \
                  --output-dir /closed-loop-e2e/experiments/dp_test/diffusionplanner/split_${SPLIT}_rr_${REPLAN_RATE}_ef_${EVAL_FRAMES} \
                  --replan-rate ${REPLAN_RATE} \
                  --eval-frames ${EVAL_FRAMES} \
                  --scene-list /closed-loop-e2e/navhard_test_split/${SPLIT}.txt
          resources:
            requests:
              cpu: "3"
              memory: "20Gi"
              nvidia.com/gpu: "1"
              ephemeral-storage: 100Gi
            limits:
              cpu: "4"
              memory: "24Gi"
              nvidia.com/gpu: "1"
              ephemeral-storage: 100Gi
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: avl-west-vol
              mountPath: /avl-west
            - name: closed-loop-e2e
              mountPath: /closed-loop-e2e
            - name: hugsim-storage
              mountPath: /hugsim-storage
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: avl-west-vol
          persistentVolumeClaim:
            claimName: avl-west-vol
        - name: closed-loop-e2e
          persistentVolumeClaim:
            claimName: closed-loop-e2e
        - name: hugsim-storage
          persistentVolumeClaim:
            claimName: horuan-hugsim-vol
      tolerations:
        - effect: NoSchedule
          key: nautilus.io/reservation
          operator: Equal
          value: cogrob
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: In
                    values:
                      - us-west
                  - key: nvidia.com/gpu.product
                    operator: In
                    values:
                      - NVIDIA-GeForce-RTX-4090
                      - NVIDIA-GeForce-RTX-3090
                    # - NVIDIA-RTX-A5000
                    # - Quadro-RTX-6000
                    # - NVIDIA-TITAN-RTX
                    # - NVIDIA-A10
                    # - Tesla-V130-SXM2-32GB
                    # - NVIDIA-A40
                    # - NVIDIA-RTX-A6000
                    # - Quadro-RTX-8000
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - ry-gpu-01.sdsc.optiputer.net
                      - ry-gpu-02.sdsc.optiputer.net
                      - ry-gpu-03.sdsc.optiputer.net
                      # - ry-gpu-04.sdsc.optiputer.net
                      # - ry-gpu-05.sdsc.optiputer.net
                      # - ry-gpu-06.sdsc.optiputer.net
                      # - ry-gpu-07.sdsc.optiputer.net
                      # - ry-gpu-08.sdsc.optiputer.net
                      # - ry-gpu-09.sdsc.optiputer.net
                      # - ry-gpu-10.sdsc.optiputer.net
                      # - ry-gpu-11.sdsc.optiputer.net
                      # - ry-gpu-12.sdsc.optiputer.net
                      # - ry-gpu-13.sdsc.optiputer.net
                      # - ry-gpu-14.sdsc.optiputer.net
