apiVersion: v1
kind: Pod
metadata:
  name: tingji-dual-mount-pod
  labels:
    app: tingji-dual-mount
spec:
  activeDeadlineSeconds: 604800  # 14 days (14 * 24 * 60 * 60)
  containers:
    - name: tingji-container
      image: hann4266/uniad:latest
      command: ["sh", "-c", "sleep infinity"]
      resources:
        requests:
          cpu: "4"
          memory: "32Gi"
          nvidia.com/gpu: "1"
          ephemeral-storage: 100Gi
        limits:
          cpu: "4"
          memory: "32Gi"
          nvidia.com/gpu: "1"
          ephemeral-storage: 100Gi
      env:
        - name: HF_HOME
          value: "/mnt/storage/huggingface"
      volumeMounts:
        - name: dshm
          mountPath: /dev/shm
        - name: tingji-storage
          mountPath: /mnt/storage
        - name: zihan-storage
          mountPath: /mnt/zihan
        - name: cogrob-storage
          mountPath: /mnt/cogrob
  restartPolicy: Never
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
    - name: tingji-storage
      persistentVolumeClaim:
        claimName: tingji-loki-pvc
    - name: zihan-storage
      persistentVolumeClaim:
        claimName: zihan-west-vol
    - name: cogrob-storage
      persistentVolumeClaim:
        claimName: cogrob-avl-west-vol
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-GeForce-RTX-3090
            - NVIDIA-GeForce-RTX-4090
            - NVIDIA-A40
            - NVIDIA-RTX-A6000
